name:                uniquely-represented-sets
version:             0.1.0.0
github:              "oisdk/uniquely-represented-sets"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/oisdk/uniquely-represented-sets#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - deepseq
  - containers

tests:
  uniquely-represented-sets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniquely-represented-sets
    - QuickCheck
    - doctest
    - checkers
    - containers

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - uniquely-represented-sets
    - criterion
    - random
